/// 组装完整的 Dart 源文件（头部注释 + import + StatelessWidget 外壳）。
///
/// 纯字符串处理，**不 import `package:flutter/*`**。
library;

import 'dart_emitter.dart';

/// 生成文件顶部标记。
const String kGeneratedHeader =
    '// GENERATED BY tool/ui_editor.dart — 再次保存会覆盖本文件，请勿手工改动。';

/// 把组件树生成为完整的 `StatelessWidget` 源码。
///
/// 生成的代码按 `dart format` 默认风格书写，且**构造即满足**项目启用的全部
/// lint（`prefer_const_constructors` / `prefer_single_quotes` /
/// `sort_constructors_first` / `always_declare_return_types` 等），因此可以安全地
/// 提交进仓库而不会让 `flutter analyze` 变红。
String generateSource({required String className, required UiNode root}) {
  final emitter = DartEmitter();
  final body = emitter.emit(root);

  final imports = <String>{
    'package:flutter/material.dart',
    ...emitter.usedImports,
  };
  final ordered = imports.toList()..sort(_compareImports);

  final buffer = StringBuffer()
    ..writeln(kGeneratedHeader)
    ..writeln();
  for (final import in ordered) {
    buffer.writeln("import '$import';");
  }
  buffer
    ..writeln()
    ..writeln('/// 由可视化编辑器生成的界面。')
    ..writeln('class $className extends StatelessWidget {')
    ..writeln('  const $className({super.key});')
    ..writeln()
    ..writeln('  @override')
    ..writeln('  Widget build(BuildContext context) {')
    ..writeln('    return $body;')
    ..writeln('  }')
    ..writeln('}');
  return buffer.toString();
}

/// `dart:` 前缀排在前面，其余按字母序。
int _compareImports(String a, String b) {
  final aIsDart = a.startsWith('dart:');
  final bIsDart = b.startsWith('dart:');
  if (aIsDart != bIsDart) {
    return aIsDart ? -1 : 1;
  }
  return a.compareTo(b);
}
